Repository software-mansion/live-debugger, pull requests merged in 2025-04, with the labels that each got.

#230 Fix: add feature flag for pulse
  lib/live_debugger/live_views/sidebar_live.ex
Labels: bug

#241 Task: introduce wallaby based testing
  .github/workflows/elixir-ci.yaml
  config/config.exs
  dev/endpoint.ex
  dev/live_components/send.ex
  dev/live_views/main.ex
  dev/runner.ex
  lib/live_debugger.ex
  lib/live_debugger/components.ex
  lib/live_debugger/env.ex
  lib/live_debugger/live_views/live_views_dashboard_live.ex
  mix.exs
  mix.lock
  test/live_debugger/channel_dashboard_test.exs
  test/live_debugger/dev_app_test.exs
  test/live_debugger/live_views_dashboard_test.exs
  test/support/e2e_case.ex
  test/test_helper.exs
Labels: testing

#274 Refactor: Garbage collection of ets tables, non-atom table id
  lib/live_debugger/gen_servers/callback_tracing_server.ex
  lib/live_debugger/live_views/channel_dashboard_live.ex
  lib/live_debugger/live_views/traces_live.ex
  lib/live_debugger/services/trace_service.ex
  lib/live_debugger/utils/pubsub.ex
  test/live_debugger/channel_dashboard_test.exs
Labels: enhancement, refactor
