Repository software-mansion/live-debugger, pull requests merged in 2025-03, with the labels that each got.

#179 Bug: Fix collapsible section closing on desktop view
  lib/live_debugger/components.ex
  lib/live_debugger/components/tree.ex
Labels: bug

#182 Task: Refactor - don't render trace body when traces loaded from historical
  lib/live_debugger/live_components/traces_list.ex
  lib/live_debugger/structs/trace_display.ex
Labels: refactor

#180 Bug: Fix unexpected exit when getting state
  lib/live_debugger/services/system/process_service.ex
  test/services/channel_service_test.exs
  test/support/system_case.ex
Labels: bug

#194 Task: fix code reloading
  config/config.exs
  dev/runner.ex
  lib/live_debugger.ex
  lib/live_debugger/endpoint.ex
  mix.exs
Labels: enhancement

#220 Fix: devtools extension error info
  devtools/devtools.js
  devtools/panel.js
Labels: bug

#221 Fix: browser features not working with embedded live views in controller
  assets/js/client.js
  devtools/devtools.js
Labels: bug

#187 Feature: components highlighting
  assets/css/themes/dark.css
  assets/css/themes/light.css
  assets/js/client.js
  assets/js/client/debug_button.js
  assets/js/client/highlight.js
  assets/js/hooks.js
  assets/js/hooks/highlight.js
  assets/js/hooks/tooltip.js
  assets/tailwind.config.js
  lib/live_debugger.ex
  lib/live_debugger/components.ex
  lib/live_debugger/components/tree.ex
  lib/live_debugger/live_components/sidebar.ex
  priv/static/app.css
Labels: enhancement
